# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(verbose_name='date searched')),
            ],
        ),
    ]
