# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 07:18
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_myuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='guest', max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='my_user',
        ),
    ]
